Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    # config.vm.network "private_network", :type => "dhcp"#,
    #    :ip => "192.168.200.0", :netmask => "255.255.255.0"
#    config.vm.synced_folder("/home/r/src/devstack", "/home/vagrant/devstack")
    #config.vm.synced_folder("/Users/apple/src/myutils", "/home/vagrant/myutils")
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    config.vm.define :default do |cfg|
        config.vm.box_check_update = false
        config.vm.network :private_network, ip:"192.168.100.49"
        config.vm.provider "virtualbox" do |v|
            v.memory = 2500
            v.cpus = 2
        end
    end

    # Trusty devstack
    config.vm.define :dstrusty do |cfg|
        config.vm.network :private_network, ip:"192.168.100.51"
        config.vm.box = "ubuntu/trusty64"
        config.vm.provider "virtualbox" do |v|
            v.memory = 4000
            v.cpus = 4
        end
    end

    config.vm.define :crdb do |cfg|
        config.vm.box_check_update = false
        config.vm.network :private_network, ip:"192.168.100.54"
        config.vm.provider "virtualbox" do |v|
            #v.gui = true
            v.memory = 4500
            v.cpus = 4
        end
    end

    # Docker
    config.vm.define :dk do |cfg|
        config.vm.box_check_update = false
        config.vm.network :private_network, ip:"192.168.100.50"
        config.vm.synced_folder("/Users/apple/src/myutils", "/home/ubuntu/myutils")
        config.vm.box = "ubuntu/xenial64"
        config.vm.provider "virtualbox" do |v|
            #v.gui = true
            v.memory = 4500
            v.cpus = 4
        end
    end

    # Cassandra 1
    config.vm.define :cass1 do |cfg|
        config.vm.box_check_update = false
        config.vm.network :private_network, ip:"192.168.100.55"
        config.vm.synced_folder("/Users/apple/src/myutils", "/home/ubuntu/myutils")
        config.vm.box = "ubuntu/trusty64"
        config.vm.provider "virtualbox" do |v|
            #v.gui = true
            v.memory = 2500
            v.cpus = 1
        end
    end

    # Cassandra 2
    config.vm.define :cass2 do |cfg|
        config.vm.box_check_update = false
        config.vm.network :private_network, ip:"192.168.100.56"
        config.vm.synced_folder("/Users/apple/src/myutils", "/home/vagrant/myutils")
        config.vm.box = "cass"
        config.vm.provider "virtualbox" do |v|
            #v.gui = true
            v.memory = 2500
            v.cpus = 1
        end
    end


#    # Vitess VM
#    config.vm.define :vt2 do |cfg|
#        cfg.vm.box = "ubuntu/trusty64"
#        cfg.vm.hostname = "vt.example.com"
#        config.vm.provider "virtualbox" do |v|
#            v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
#            v.memory = 2000
#            v.cpus = 1
#        end
#    end
#    config.vm.define :db do |cfg|
#        cfg.vm.hostname = "mysql.example.com"
#        cfg.vm.network :private_network, ip: "192.168.200.55"
#        config.vm.provider "virtualbox" do |v|
#            v.memory = 500
#            v.cpus = 1
#        end
#    end
#
#    # C is for cassandra
#    config.vm.define :c do |cfg|
#        cfg.vm.hostname = "cassandra.example.com"
#        cfg.vm.network :private_network, ip: "192.168.200.56"
#        cfg.vm.network :forwarded_port, guest: 22, host: 12222
#        config.vm.provider "virtualbox" do |v|
#            v.memory = 2000
#            v.cpus = 1
#        end
#    end
#
#    # VM for citrix receiver
#    config.vm.define :citrix do |cfg|
#        cfg.vm.network :forwarded_port, guest: 22, host: 2223
#        cfg.vm.hostname = "citrix.example.com"
#        cfg.vm.network :private_network, ip: "192.168.200.57"
#        config.vm.provider "virtualbox" do |v|
#            v.memory = 1000
#            v.cpus = 1
#        end
#    end
#
#    config.vm.define :libertykscass do |cfg|
#        config.vm.box = "devstack-liberty-6june"
#        cfg.vm.hostname = "ds.example.com"
#        config.vm.network :private_network, ip:"192.168.100.59"
#        config.vm.provider "virtualbox" do |v|
#            v.memory = 3000
#            v.cpus = 1
#        end
#    end
#
#    config.vm.define :docker do |cfg|
#        config.vm.box = "ubuntu/trusty64"
#        cfg.vm.hostname = "dock.example.com"
#        config.vm.network :private_network, ip:"192.168.100.60"
#        config.vm.provider "virtualbox" do |v|
#            v.memory = 2000
#            v.cpus = 1
#        end
#    end
#
#    config.vm.define :nova do |cfg|
#        config.vm.box = "devstack-liberty-6june"
#        cfg.vm.hostname = "ds.example.com"
#        config.vm.network :private_network, ip:"192.168.100.61"
#        config.vm.provider "virtualbox" do |v|
#            v.memory = 3000
#            v.cpus = 1
#        end
#    end
#
#    config.vm.define :go do |cfg|
#        cfg.vm.box = "ubuntu/trusty64"
#        cfg.vm.hostname = "go.example.com"
#        config.vm.network :private_network, ip:"192.168.100.62"
#        config.vm.provider "virtualbox" do |v|
#            v.memory = 1000
#            v.cpus = 1
#        end
#    end
#
#    config.vm.define :djangotest do |cfg|
#        cfg.vm.box = "ubuntu/trusty64"
#        cfg.vm.hostname = "dj.example.com"
#        config.vm.network :private_network, ip:"192.168.100.63"
#        config.vm.provider "virtualbox" do |v|
#            v.memory = 1000
#            v.cpus = 2
#        end
#    end
#
#    config.vm.define :rr do |cfg|
#        cfg.vm.box = "ubuntu/trusty64"
#        cfg.vm.hostname = "rr.example.com"
#        config.vm.network :private_network, ip:"192.168.100.64"
#        config.vm.provider "virtualbox" do |v|
#            v.memory = 1000
#            v.cpus = 2
#        end
#    end
#
#    config.vm.define :temp do |cfg|
#        cfg.vm.box = "ubuntu/trusty64"
#        cfg.vm.hostname = "rr.example.com"
#        config.vm.network :private_network, ip:"192.168.100.65"
#        config.vm.provider "virtualbox" do |v|
#            v.memory = 1000
#            v.cpus = 2
#        end
#    end

end
