alias au='sudo apt-get update'
alias ai='sudo apt-get install'
alias auy='sudo apt-get update --assume-yes'
alias aiy='sudo apt-get install --assume-yes'
alias aac='sudo apt-get autoclean'
alias aar='sudo apt-get autoremove'
alias ap='sudo apt-get purge'
alias ar='sudo apt-get remove'
alias ad='sudo apt-get dist-upgrade'
alias aud='sudo apt-get update --assume-yes && sudo apt-get dist-upgrade --assume-yes'

