alias au='sudo -E apt-get update --assume-yes'
alias ai='sudo -E apt-get install --assume-yes'
alias aud='sudo -E apt-get update --assume-yes && sudo -E apt-get dist-upgrade --assume-yes'
alias aac='sudo -E apt-get autoclean'
alias aar='sudo -E apt-get autoremove'
alias ap='sudo -E apt-get purge'
alias ar='sudo -E apt-get remove'
alias ad='sudo -E apt-get --assume-yes dist-upgrade'

alias auy='sudo -E apt-get update'
alias aiy='sudo -E apt-get install'
alias audy='sudo -E apt-get update && sudo -E apt-get dist-upgrade'
alias ady='sudo -E apt-get dist-upgrade'

alias dpg='dpkg -l | grep -i'
