#! /bin/bash
if [ $(ps aux | awk '{print $11}' | grep -c rescuetime) == 0 ]; then
    echo 'RescueTime not running. Attempting to start..'
    /usr/bin/rescuetime &
    echo 'RescueTime started hopefully.'
else
    echo 'rescuetimealreadyrunning'
fi
